### ISSUE TITLE
Home page fails to compel readers

### ISSUE THREAD

**Issue by adamn-ntap** [NetAppDocs/hybridcloudsolutions#13]
We're missing a golden opportunity in the first paragraph of the home page for Hybrid Cloud Solutions - https://docs.netapp.com/us-en/hybridcloudsolutions/index.html.

Specifically, we're not motivating readers by telling them what the solutions are and how they help them solve their business problems. Instead, we're providing a functional spec-like sentence as follows:

>> The Hybrid Cloud Solutions page takes a solutions level approach to enabling customers on their cloud journey.

Customers are not motivated by statements about enabling customers.

Contrast this opening paragraph with the same from the OCCM home page - https://docs.netapp.com/us-en/occm/index.html. You can also consult the opening paragraphs from the other services to discern the pattern.

Please re-write the first paragraph to give the reader a reason to keep browsing.

**Comment by ntap-bmegan** [comment]
Repo has had only administrative updates since 2018. 

https://github.com/NetAppDocs/hybridcloudsolutions/commits/main
