### ISSUE TITLE
Link to HCI Solutions Page?

### ISSUE THREAD

**Issue by vBiggles1** [NetAppDocs/hybridcloudsolutions#19]
Page: [Hybrid Cloud Solutions](https://docs.netapp.com/us-en/hybridcloudsolutions/index.html)

Hi Team,

Would you consider linking the new HCI Solutions (given this is our Hybrid Cloud Platform) from this page?

https://docs.netapp.com/us-en/hci/solutions/index.html is the link.

Cheers

Matt

**Comment by ntap-bmegan** [comment]
This issue will be closed on tues 30 aug 2022 due to lack of activity within the last 30 days. @vBiggles1 - If you believe that the original problem persists, please comment in this issue to keep it open for further review.

**Comment by ntap-bmegan** [comment]
This issue has been closed due to inactivity. Any interested party can comment to reopen the issue.
